In [1]:
import pandas as pd
import numpy as np

# 1. Annotation Training set

In [24]:
annoted_df = pd.read_parquet("data/annotation/prompt_v5/training_set_labeled.parquet")
annoted_df

,ID_JOCAS,annee,mois,entreprise_nom,location_zipcode,description,job_ROME_code,contractType,SIREN,NAF_Code,...,schedule_flexibility,on_the_job_training,internal_career_progression,company_culture,non_salary_benefits,work_meaning_impact,junior_offer,experienced_offer,very_experienced_offer,manager_offer
0,REGIONSJOB_PARIS_2019-01-30_413,2019,1,bouygues-immobilier,92130.0,<br/>nous vous proposons de rejoindre une équi...,M1803,NaN,562091546,41.10A,...,0,0,0,1,0,1,0,1,0,0
1,JOBINTREE_2019-07-25_241,2019,7,NaN,71100.0,vous êtes directement rattaché à la direction ...,M1206,CDI,,,...,0,0,0,0,0,0,0,1,0,0
2,APEC_2021-07-13_567,2021,7,bleu libellule,NaN,et si vous rejoigniez bleu libellule en tant...,M1402,CDI,,,...,0,0,1,1,1,0,0,1,0,1
3,VIADEO_2019-04-11_1413,2019,4,aravati,75000.0,"doté de bonnes capacités relationnelles, le re...",M1803,CDI,477638068,70.22Z,...,0,0,0,0,0,0,0,1,0,0
4,apec_2024-03-15_6633,2024,3,NaN,NaN,prêts à relever des nouveaux défis ? vous avez...,M1802,CDI,,,...,0,0,0,0,0,0,0,1,0,0
5,api_poleemploi_2024-07-15_1012,2024,7,effilab,92100,notre produit :\nle produit booster contact co...,M1704,CDI,531205565,70.22Z,...,0,1,0,1,0,0,0,0,0,0
6,API_POLEEMPLOI_2021-04-04_9048,2021,4,NaN,NaN,poste : technicien informatique h/f\nprofil : ...,M1810,CDI,,,...,0,0,0,0,0,1,0,0,0,0
7,API_POLEEMPLOI_2021-12-10_50169,2021,12,NaN,NaN,description de l'entreprisesofitex experts sai...,M1803,CDI,,,...,0,0,0,0,0,0,0,0,0,0
8,METEOJOB_2020-12-21_5687,2020,12,speaking-agency,75000,description du poste garde d'enfants à domicil...,K1303,CDD,511779738,85.60Z,...,0,0,0,0,0,0,0,1,0,0
9,api_poleemploi_2022-07-29_6420,2022,7,NaN,14860.0,description entreprisewanteez by h&l intervie...,K1304,CDI,,,...,0,0,0,0,0,0,0,0,0,0
10,API_POLEEMPLOI_2021-12-19_9899,2021,12,NaN,91150.0,encore 2 postes à pourvoir sur les 4 recherché...,K1303,CDI,,,...,0,0,0,0,0,0,0,0,0,0
11,hellowork_commercial_particulier_2022-12-23_801,2022,12,sintel,75000.0,type de contratcdi lieuparis salaire € posté...,D1408,CDI,347720773,78.20Z,...,0,0,1,1,0,0,0,1,0,0
12,api_poleemploi_2023-05-19_3727,2023,5,ras 1040,44210,vous avez soif d'aventures et de nouveaux défi...,D1403,MIS,,,...,0,1,1,0,1,0,0,1,0,0
13,JOBINTREE_2019-11-21_8842,2019,11,sella conseils,NaN,sella conseils est un cabinet de recrutement f...,D1401,CDI,818052144,62.02A,...,0,0,0,0,0,0,0,0,0,1
14,JOBINTREE_2019-12-05_24176,2019,12,trescal somelec,94150.0,"rattaché(e) à notre agence de rungis, votre mi...",H1102,CDD,,,...,0,0,0,0,0,0,0,1,0,0
15,API_POLEEMPLOI_2020-10-02_5451,2020,10,NaN,77127.0,description du poste :\nvous serez chargé de l...,H2502,MIS,,,...,0,0,0,0,0,0,0,0,0,0
16,JOBINTREE_2021-08-12_10573,2021,8,axelis,NaN,description du poste :absolis intérim recherch...,H2206,MIS,515347565,35.11Z,...,0,0,0,0,0,0,0,1,0,0
17,APEC_2021-11-29_5620,2021,11,idverde,8000.0,idverde recherche un conducteur de travaux se...,F1201,CDI,339609661,81.30Z,...,0,0,0,0,0,1,0,1,0,1
18,API_POLEEMPLOI_2020-01-22_4363,2020,1,adwork's travail temporaire,35000.0,vous êtes peintre en bâtiment et à la recherch...,F1606,MIS,,,...,0,0,0,0,0,0,0,0,0,0
19,hellowork_btp_gros_second_oeuvre_2024-06-10_38443,2024,6,optineris,24000,vous justifiez d'une expérience dans le bâtime...,F1704,MIS,408415149,64.20Z,...,0,0,0,0,0,0,0,1,0,0
20,JOBINTREE_2019-12-20_1243,2019,12,feu vert services,69700.0,vos missions : grâce à vos compétences techni...,I1604,CDI,,,...,0,0,0,0,0,0,0,0,0,0
21,REGIONSJOB_PACA_2022-03-08_308,2022,3,first stop ayme,83170.0,bridgestone bénéficie de 17 partenaires détai...,I1604,CDI,722620119,45.31Z,...,0,1,1,1,1,1,0,0,0,0
22,JOBINTREE_2020-01-25_27004,2020,1,alarm'com,14123.0,votre mission : vous effectuerez l'installatio...,I1307,CDI,,,...,0,0,0,0,0,0,0,0,0,0
23,jobintree_2024-01-12_504,2024,1,del arte,11000,description du poste :dans une équipe de 5 per...,G1602,CDI,,,...,0,0,0,0,0,0,0,0,0,0
24,jobintree_2022-05-30_81224,2022,5,jelc,29200.0,description du poste :vous serez en charge du ...,G1803,CDI,,,...,0,0,0,0,0,0,0,0,0,0
25,JOBINTREE_2021-03-30_12819,2021,3,sodexho,30170.0,description du poste :poste à pourvoir dés que...,G1605,CDD,,,...,0,0,0,0,0,0,0,0,0,0
26,API_POLEEMPLOI_2021-07-02_15740,2021,7,NaN,94140.0,pour l'ouverture de notre micro-crèche de 10 p...,J1507,CDI,,,...,0,0,0,1,0,1,0,0,0,1
27,api_poleemploi_2022-11-05_1063,2022,11,elsan,33600.0,**contexte établissement/service :**\ninstallé...,J1506,CDI,802798934,66.30Z,...,0,1,1,1,1,1,1,0,0,0
28,API_POLEEMPLOI_2021-05-08_27915,2021,5,l'appel médical,86200.0,rejoignez les 30 000 collaborateurs de l'appel...,J1501,CDI,,,...,0,0,0,0,0,1,0,0,0,0
29,hellowork_btp_gros_second_oeuvre_2023-06-09_1735,2023,6,groupe berto,69800.0,vous disposez d'une réelle capacité d'adaptat...,N4101,CDI,780077798,77.12Z,...,0,1,1,1,1,0,0,1,0,0
30,jobintree_2023-11-15_20468,2023,11,equans,59700,description du poste :axima fait partie de l'e...,N1303,CDI,351984448,43.22B,...,0,0,0,0,0,1,0,1,0,0
31,api_poleemploi_2024-06-07_1074,2024,6,partnaire 67,67500,"notre client, enseigne de la grande distributi...",N1103,MIS,,,...,0,0,0,1,1,0,0,0,0,0
32,api_poleemploi_2024-06-08_16304,2024,6,safti,59282,lancez-vous dans l'immobilier avec safti !pour...,C1504,CDI,523964328,68.31Z,...,1,1,0,0,0,1,1,0,0,0
33,api_poleemploi_2022-10-08_40767,2022,10,laforêt france,NaN,"au sein de l'agence, vous serez en charge de t...",C1504,CDI,502922248,82.99Z,...,0,1,0,0,0,1,0,0,0,0
34,API_POLEEMPLOI_2021-09-19_16533,2021,9,NaN,69150.0,"engie home services (4200 personnes, 250 sites...",C1102,CDD,,,...,0,0,1,1,1,0,0,0,0,0
35,apec_2023-05-25_6523,2023,5,groupement vinci construction / webuild - proj...,73140,"rattaché.e au responsable environnement, vou...",A1303,Alternance,,,...,0,0,0,0,0,1,1,0,0,0
36,JOBINTREE_2020-09-03_41939,2020,9,gamm vert services,17620.0,gamm vert st agnant recherche un(e) jeune moti...,A1203,CDD,,,...,0,1,0,0,0,0,1,0,0,0
37,jobintree_2022-07-05_24673,2022,7,domaine beausejour,37220.0,description du poste :vous intégrez notre équi...,A1405,CDD,,,...,0,1,1,0,1,0,1,0,0,0
38,jobintree_2023-08-01_23932,2023,8,au boulot,31190,description du poste :aujourd'hui plus que dem...,E1103,CDI,,,...,0,0,0,0,0,0,0,1,0,0
39,jobintree_2023-10-19_38802,2023,10,groupe france textile production,31770,"description du poste :depuis 1993, france text...",E1103,CDI,,,...,0,1,0,1,0,0,0,1,0,1
40,API_POLEEMPLOI_2021-11-16_27361,2021,11,apdgo,35000.0,cadre de la mission :\n- placé.e sous l'autori...,E1103,CDI,,,...,0,0,0,0,0,0,0,0,0,0
41,hellowork_restauration_hotellerie_tourisme_202...,2023,6,NaN,NaN,missions assure l'animation et l'encadrement...,,NaN,,,...,0,0,0,0,0,1,1,0,0,0
42,jobintree_2023-01-23_22876,2023,1,monreseau-immo.com,69960,description du poste :*annonce expirée* un rés...,,NaN,,,...,0,1,0,0,0,0,1,0,0,0
43,hellowork_assistanat_admin_accueil_2023-04-27_...,2023,4,NaN,NaN,"polyvalent.e, vous pourrez débuter votre jou...",,NaN,,,...,0,1,0,0,0,1,1,0,0,0
44,hellowork_dir_management_resp_2024-04-27_127,2024,4,morgan services,49400,vous intervenez sur des produits à hautes exig...,B1603,NaN,722023728,78.20Z,...,0,0,0,0,0,0,0,0,0,0
45,JOBINTREE_2021-06-09_8432,2021,6,noz,53000.0,description du poste :vous êtes à la recherche...,B1601,CDD,432316388,68.20B,...,0,1,1,0,0,0,0,1,0,0
46,JOBINTREE_2019-02-16_10833,2019,2,NaN,NaN,"au sein d'une bijouterie, proposant des créati...",B1603,CDI,,,...,0,0,0,0,0,0,0,1,0,0
47,api_poleemploi_2022-10-10_18403,2022,10,NaN,93500.0,nous recherchons des artistes de cirque pour r...,L1204,CDI,,,...,0,0,0,0,0,1,0,0,0,0
48,hellowork_metiers_fonction_publique_2024-02-17...,2024,2,armée de terre,52000,"vos qualités : passionné, ouvert d'esprit, rig...",L1202,NaN,110090016,84.11Z,...,0,0,0,0,0,0,1,0,0,0
49,jobintree_2023-04-09_30713,2023,4,mydigitalschool,NaN,description du poste :mydigitalschool montpell...,L1507,Alternance,522823681,64.20Z,...,0,1,1,0,0,0,1,0,0,0

In [25]:
annoted_df.shape

(50, 32)

In [27]:
LABELS = [ 
    "remote_work",
    "schedule_flexibility",
    "on_the_job_training",
    "internal_career_progression",
    "company_culture",
    "non_salary_benefits",
    "work_meaning_impact",
    "junior_offer",
    "experienced_offer",
    "very_experienced_offer",
    "manager_offer",
]

In [26]:
annoted_df.columns

Index(['ID_JOCAS', 'annee', 'mois', 'entreprise_nom', 'location_zipcode',
       'description', 'job_ROME_code', 'contractType', 'SIREN', 'NAF_Code',
       'Employee_Range', 'Company_Category', 'Director_Birth_Year',
       'Company_Creation_Date', 'description_clean', 'embedding',
       'embedding_pca', 'job_title', 'job_title_clean', 'rome_domain',
       '_annotation_id', 'remote_work', 'schedule_flexibility',
       'on_the_job_training', 'internal_career_progression', 'company_culture',
       'non_salary_benefits', 'work_meaning_impact', 'junior_offer',
       'experienced_offer', 'very_experienced_offer', 'manager_offer'],
      dtype='str')

In [30]:
test = annoted_df[annoted_df[LABELS[4]]==1]
test = test.iloc[0:10]
test[['entreprise_nom', 'description', 'job_title', 'remote_work', 'schedule_flexibility',
       'on_the_job_training', 'internal_career_progression', 'company_culture',
       'non_salary_benefits', 'work_meaning_impact', 'junior_offer',
       'experienced_offer', 'very_experienced_offer', 'manager_offer']]

,entreprise_nom,description,job_title,remote_work,schedule_flexibility,on_the_job_training,internal_career_progression,company_culture,non_salary_benefits,work_meaning_impact,junior_offer,experienced_offer,very_experienced_offer,manager_offer
0,bouygues-immobilier,<br/>nous vous proposons de rejoindre une équi...,Responsable de Projets H/F,0,0,0,0,1,0,1,0,1,0,0
2,bleu libellule,et si vous rejoigniez bleu libellule en tant...,Animateur de Réseau F/H,1,0,0,1,1,1,0,0,1,0,1
5,effilab,notre produit :\nle produit booster contact co...,Account Coordinator H/F,0,0,1,0,1,0,0,0,0,0,0
11,sintel,type de contratcdi lieuparis salaire € posté...,Conseiller Clients - Bilingue Allemand et Angl...,1,0,0,1,1,0,0,0,1,0,0
21,first stop ayme,bridgestone bénéficie de 17 partenaires détai...,monteur-de-pneus,0,0,1,1,1,1,1,0,0,0,0
26,NaN,pour l'ouverture de notre micro-crèche de 10 p...,Directeur/Directrice micro-crèche (H/F),0,0,0,0,1,0,1,0,0,0,1
27,elsan,**contexte établissement/service :**\ninstallé...,Infirmier / Infirmière de soins généraux (H/F),0,0,1,1,1,1,1,1,0,0,0
29,groupe berto,vous disposez d'une réelle capacité d'adaptat...,Chauffeur PL Grue Auxiliaire H/F,0,0,1,1,1,1,0,0,1,0,0
31,partnaire 67,"notre client, enseigne de la grande distributi...",Préparateur de commandes (H/F),0,0,0,0,1,1,0,0,0,0,0
34,NaN,"engie home services (4200 personnes, 250 sites...",CONSEILLER.E CLIENTELE CDD > Lyon Décines (H/F),0,0,0,1,1,1,0,0,0,0,0

In [33]:
test.iloc[3]['description']

"  type de contratcdi lieuparis salaire € posté22/12/2022 save job sintel recrutement description du poste share - copy link. - e-mail. - facebook. - whatsapp. jquery(function(){ //jquery(.tertiary).on(click,#sharemy, function(){ jquery(#sharemy).click(function(){ jquery(this).next().toggle()., jquery(#copy).click(function() { //jquery(.tertiary).on(click,#copy, function(){ var content = jquery(this).attr(share-link)., var clipboard = new clipboard('#copy', { text : function() { return content., } clipboard.on('success', function(e) { alert()., clipboard.on('error', function(e) { console.log(e)., }) })., l'entreprise sintel recrute pour l'un de ses clients, maison de pap luxe, un customer service h/f les missions : vous assurez un conseil personnalisé auprès d'une clientèle internationale exigeante pour des enseignes de prestige. vos missions : - réponse aux diverses questions clients au niveau international. - gestion des demandes d'avoir, des bons de retour et réexpédition sav. - traitement des réclamations et litiges clients. - interface avec l'équipe e-commerce. - relations et communication avec les différents départements et services internes. - participation à la démarche d'amélioration continue de l'expérience client. - reporting hebdomadaire et mensuel. liste non exhaustive. en contact permanent avec la clientèle, vous intervenez sur tout type de support (téléphone, mails, réseaux sociaux...). quelques lignes sur vous : de formation supérieure, vous justifiez d'une expérience significative en contact direct du client. une expérience dans une maison de luxe serait un vrai plus. vous maîtrisez le pack office et un crm. vous avez un anglais et allemand courant. vous êtes une personne proactive, dynamique et rigoureuse. curieux(se), vous êtes ouvert(e) d'esprit et faites preuve d'enthousiasme à l'idée d'acquérir de nouvelles connaissances. vous êtes également flexible et autonome et avez de bonnes aptitudes à la résolution de problème. doté(e) d'un excellent relationnel, vous avez le sens de la satisfaction client et de l'excellence. vous êtes attiré(e) par le monde du luxe et de la mode ? vous souhaitez évoluer au sein d'une entreprise à l'esprit start-up dans un environnement multiculturel ? alors n'hésitez pas, ce poste est fait pour vous ! contrat : cdd télétravail 2j/semaine -. a{color : #4d4d4d.,} postuler prénom * last name * e-mail * téléphone message cv en pj autres informations maximun file size : 5 mb accepted formats :.txt,.pdf,.doc,.docx,.ppt,.pptx  "

In [82]:
df = pd.read_parquet("data/JOCAS/jocas_small_all_half_sirenised_embed_job_title_drop_stage.parquet")

# 2. LLM Fine tuning

In [139]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

model_name = "almanach/moderncamembert-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=5)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json: 0.00B [00:00, ?B/s]

c:\Users\benjamin.lengereau\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\benjamin.lengereau\.cache\huggingface\hub\models--almanach--moderncamembert-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/544M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

ModernBertForSequenceClassification LOAD REPORT from: almanach/moderncamembert-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [140]:
classifier = pipeline("text-classification", model=model, tokenizer=tokenizer)

In [ ]:

offre = """
[Votre texte d'offre d'emploi ici]
"""
sections = [
    "Missions: participer à l’amélioration de la performance commerciale...",
    "Profil: de formation supérieure en commerce, vous justifiez d’une expérience réussie...",
    "Valeurs: audace, bienveillance, passion et ambition..."
]

for section in sections:
    result = classifier(section)
    print(f"Section: {section[:50]}... -> {result}")

# 3. High scale inference