In [2]:
import pandas as pd 
import numpy as np

# 1. Annotation Training set

In [3]:
annoted_df = pd.read_parquet("data/annotation/prompt_v6/training_set_labeled.parquet")
annoted_df

,ID_JOCAS,annee,mois,entreprise_nom,location_zipcode,description,job_ROME_code,contractType,SIREN,NAF_Code,...,junior_offer,experienced_offer,very_experienced_offer,management,programming_skills,communication_skills,creativity_skills,analytical_skills,interpersonal_skills,manual_skills
0,REGIONSJOB_PARIS_2019-01-30_413,2019,1,bouygues-immobilier,92130.0,<br/>nous vous proposons de rejoindre une équi...,M1803,NaN,562091546,41.10A,...,0,1,0,0,0,0,0,1,1,0
1,JOBINTREE_2019-07-25_241,2019,7,NaN,71100.0,vous êtes directement rattaché à la direction ...,M1206,CDI,,,...,0,1,0,0,0,1,0,1,0,0
2,APEC_2021-07-13_567,2021,7,bleu libellule,NaN,et si vous rejoigniez bleu libellule en tant...,M1402,CDI,,,...,0,1,0,1,0,1,1,1,1,0
3,VIADEO_2019-04-11_1413,2019,4,aravati,75000.0,"doté de bonnes capacités relationnelles, le re...",M1803,CDI,477638068,70.22Z,...,0,1,0,0,1,0,0,1,1,0
4,apec_2024-03-15_6633,2024,3,NaN,NaN,prêts à relever des nouveaux défis ? vous avez...,M1802,CDI,,,...,0,1,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,API_POLEEMPLOI_2022-02-16_1516,2022,2,me and my boss,NaN,la société :fondée par 3 chefs d'entreprise et...,L1302,Franchise,519880454,78.10Z,...,0,0,0,1,0,0,0,0,0,0
9996,apec_2023-04-19_3191,2023,4,editions gallimard,NaN,rattaché(e) au directeur commercial numérique...,L1507,CDI,,,...,0,1,0,0,0,0,0,1,1,0
9997,API_POLEEMPLOI_2022-03-01_46122,2022,3,me and my boss,47300.0,la société : fondée par 3 chefs d'entreprise e...,L1302,Franchise,519880454,78.10Z,...,0,0,0,1,0,0,0,0,0,0
9998,jobintree_2023-09-25_23145,2023,9,la poste service courrier colis,NaN,"description du poste :la poste groupe change, ...",L1505,CDI,,,...,0,1,0,0,0,0,0,0,1,1
9999,API_POLEEMPLOI_2021-11-28_21483,2021,11,NaN,90000.0,fort d'une expérience de plus de 30 ans dans l...,L1302,MIS,,,...,0,0,0,1,0,0,0,0,0,1

In [4]:
annoted_df.shape

(10000, 38)

In [5]:
LABELS = [ 
    "remote_work",                  # télétravail ou non
    "schedule_flexibility",         # flexibilité dans le choix des horaires
    "on_the_job_training",          # formation au travail
    "internal_career_progression",  # possibilité de carrière au sein de l'entreprise
    "company_culture",              # culture d'entreprise mise en avant
    "non_salary_benefits",          # avantages non salariaux
    "work_meaning_impact",          # sens / utilité du travail mise en avant
    "junior_offer",                 # recrute un junior
    "experienced_offer",            # recrute un expérimenté
    "very_experienced_offer",       # recrute un profil très sénior
    "management",                   # poste de management d'équipe
    "programming_skills",           # skills de développement logiciel, code
    "communication_skills",         # skills oral, écrit, présentation
    "creativity_skills",            # skills créatifs, innovants
    "analytical_skills",            # skills analytiques, solutions de problèmes
    "interpersonal_skills",         # skills de travail en équipe, négociation, leadership    
    "manual_skills",                # skills physiques, travail artisanal
]

In [6]:
print(annoted_df[LABELS].sum().sort_values())

very_experienced_offer          103
remote_work                     395
programming_skills              495
schedule_flexibility            565
junior_offer                   1134
work_meaning_impact            1174
management                     1505
creativity_skills              1508
internal_career_progression    1686
company_culture                2379
non_salary_benefits            2395
on_the_job_training            2541
analytical_skills              3027
communication_skills           3312
manual_skills                  4244
experienced_offer              4443
interpersonal_skills           6044
dtype: int64

In [82]:
print((annoted_df[LABELS].mean() * 100).sort_values())

very_experienced_offer          1.03
remote_work                     3.95
programming_skills              4.95
schedule_flexibility            5.65
junior_offer                   11.34
work_meaning_impact            11.74
management                     15.05
creativity_skills              15.08
internal_career_progression    16.86
company_culture                23.79
non_salary_benefits            23.95
on_the_job_training            25.41
analytical_skills              30.27
communication_skills           33.12
manual_skills                  42.44
experienced_offer              44.43
interpersonal_skills           60.44
dtype: float64

In [70]:
annoted_df.columns

Index(['ID_JOCAS', 'annee', 'mois', 'entreprise_nom', 'location_zipcode',
       'description', 'job_ROME_code', 'contractType', 'SIREN', 'NAF_Code',
       'Employee_Range', 'Company_Category', 'Director_Birth_Year',
       'Company_Creation_Date', 'description_clean', 'embedding',
       'embedding_pca', 'job_title', 'job_title_clean', 'rome_domain',
       '_annotation_id', 'remote_work', 'schedule_flexibility',
       'on_the_job_training', 'internal_career_progression', 'company_culture',
       'non_salary_benefits', 'work_meaning_impact', 'junior_offer',
       'experienced_offer', 'very_experienced_offer', 'management',
       'programming_skills', 'communication_skills', 'creativity_skills',
       'analytical_skills', 'interpersonal_skills', 'manual_skills'],
      dtype='str')

In [ ]:
test = annoted_df[annoted_df[LABELS[11]]==1]
test = test.iloc[70:80]
s

,entreprise_nom,description,job_title,remote_work,schedule_flexibility,on_the_job_training,internal_career_progression,company_culture,non_salary_benefits,work_meaning_impact,junior_offer,experienced_offer,very_experienced_offer,management,programming_skills,communication_skills,creativity_skills,analytical_skills,interpersonal_skills,manual_skills
394,thales,qui sommes-nous ? thales propose des systèmes ...,Tech Lead (H/F),0,0,0,1,1,0,0,0,1,0,1,1,1,1,0,1,0
403,NaN,mission : \nsous la responsabilité du chef de ...,Ingénieur / Ingénieure d'intégration applicati...,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0
411,NaN,recherche: développeur informatique ia (h/f)\n...,DÉVELOPPEUR INFORMATIQUE IA (H/F),1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0
415,td synnex,description du poste :qui sommes-nous ?td synn...,"? postulez maintenant! data analyst, en altern...",1,0,1,1,1,1,0,1,0,0,0,1,0,0,1,0,0
420,NaN,« simpliciti a été imaginée pour être le parte...,Développeur.euse PHP - Profils Expérimenté - C...,0,0,0,0,1,0,1,0,1,0,0,1,0,0,1,1,0
423,oxxeo consulting,nous recherchons un développeur python f/h pa...,Développeur Python F/H,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0
437,NaN,peoplespheres est une start-up qui édite le pr...,Data Scientist - CDI (H/F),1,0,0,0,1,1,0,0,1,0,0,1,0,1,1,1,0
438,NaN,qui sommes-nous ? thales propose des syst...,Ingénieur ivvq support essais avion système de...,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0
439,ag2r la mondiale,description du poste :qui sommes-nous ?rejoind...,CONCEPTEUR DEVELOPPEUR (H/F),0,0,0,0,0,0,1,0,1,0,0,1,0,0,1,0,0
445,NaN,projet : migration des processus d'intégration...,Lead Technique Big data H/F,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [79]:
test.iloc[4]['description']

"« simpliciti a été imaginée pour être le partenaire technologique des territoires connectés. leader des solutions embarquées pour le monde de demain, simpliciti est un acteur historique avec + de 25 ans d'existence en france et + de 5 ans sur le continent africain. nous réalisons un chiffre d'affaires de 17m€ sur 2020 avec un objectif ambitieux de 50m€ à 2025.  nous proposons des solutions matérielles et logicielles métiers avec des fonctionnalités innovantes afin d'optimiser grâce à la data - les secteurs de la collecte des déchets, le transport de voyageurs et le transport de marchandises.  appartenant au groupe berto (entreprise familiale réalisant 350 m€ de ca et 4000 collaborateurs), nous avançons grâce à notre esprit collaboratif et agile avec un projet qui a du sens en traitant au quotidien des problématiques sociétales telles que l'économie circulaire, ou l'accès à la mobilité des personnes.  nos innovations technologiques sont entièrement pensées et conçues « made in france ». inscrits dans une volonté d'apporter de nouveaux outils pour soutenir le développement des smart cities, les produits ont pour objectif d'améliorer la qualité de vie des citoyens en fournissant aux collectivités un moyen de les rendre actrice d'une économie plus circulaire.  présente en france, sur 5 sites : avignon, montpellier, aix-en-provence et valbonne et au maroc (sabatier géolocalisation), plus de 1500 acteurs du secteur privé et public font confiance à notre simpli'team au quotidien grâce au savoir-faire des 120 collaborateurs la composant ».  intégré à une équipe de développement d'une quinzaine de personnes, vous serez en charge de la maintenance évolutive et corrective de l'une de nos plateformes. offre à pourvoir sur l'un de nos sites : avignon (84), aix-en-provence (13) ou st aunès (34)  vos activités types seront les suivantes : - participer à la conception technique, au paramétrage et à la rédaction des spécifications techniques. - analyse de l'existant. - développer et maintenir des briques aussi bien backend (apis, mysql...) que frontend (jquery, css...). - développement de tests unitaires et fonctionnels. - optimiser la performance des applications. - garantir la qualité des mises en production mensuelle de de notre plateforme logicielle (via des revues de codes, revues des exécutions de campagne de tests, maintenabilité du code et production et maintien de nos documentations). - travail en équipe en méthodologie agile. - participer au traitement des priorités des flux d'anomalies clients et de recette interne qa. l'équipe produit (r&d hw, production, r&d sw, product management), c'est 50 personnes, l'équipe r&d sw c'est 25 personnes dans le sud de la france (avignon, montpellier, bordeaux, aix-en-provence).  nos challenges sont nombreux, que ce soit métiers (l'internationalisation, cartographie, optimisation de circuits, des intégrations à des services tiers, expérience utilisateur multi-canal etc.) ou techniques (la scalabilité, la tenue en char vous avez une expérience significative d'au moins 5 ans dans le développement de solution s'appuyant sur des framework du marché php &gt.,= 5.5, symfony &gt.,= 3.4, api platform, mysql, mongodb, nodejs, web, jquery  une expérience dans les technologies js telles que vuejs 2/3, css3, pug/jade et les technologies de carto telles que leaflet, axios, google map api serait un plus.  vous êtes rodé au développement de tests unitaires et fonctionnels (jest/mocha et selenium/puppeteer)  vous connaissez également les technologies suivantes : webpack, sass, nodejs  vous être prêt à prendre en main la maintenance d'un système existant avec des technologies multiples et mettre les mains dans le cambouis pour résoudre des problèmes complexes et/ou urgents. vous avez une expérience significative d'au moins 5 ans dans le développement de solution s'appuyant sur des framework du marché php &gt.,= 5.5, symfony &gt.,= 3.4, api platform, mysql, mongodb, nodejs, web, jquery  une expérience dans les technologies js telles que vuejs 2/3, css3, pug/jade et les technologies de carto telles que leaflet, axios, google map api serait un plus.  vous êtes rodé au développement de tests unitaires et fonctionnels (jest/mocha et selenium/puppeteer)  vous connaissez également les technologies suivantes : webpack, sass, nodejs  vous être prêt à prendre en main la maintenance d'un système existant avec des technologies multiples et mettre les mains dans le cambouis pour résoudre des problèmes complexes et/ou urgents."

In [82]:
df = pd.read_parquet("data/JOCAS/jocas_small_all_half_sirenised_embed_job_title_drop_stage.parquet")

# 2. LLM Fine tuning

In [139]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

model_name = "almanach/moderncamembert-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=5)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json: 0.00B [00:00, ?B/s]

c:\Users\benjamin.lengereau\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\benjamin.lengereau\.cache\huggingface\hub\models--almanach--moderncamembert-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/544M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

ModernBertForSequenceClassification LOAD REPORT from: almanach/moderncamembert-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [140]:
classifier = pipeline("text-classification", model=model, tokenizer=tokenizer)

In [ ]:

offre = """
[Votre texte d'offre d'emploi ici]
"""
sections = [
    "Missions: participer à l’amélioration de la performance commerciale...",
    "Profil: de formation supérieure en commerce, vous justifiez d’une expérience réussie...",
    "Valeurs: audace, bienveillance, passion et ambition..."
]

for section in sections:
    result = classifier(section)
    print(f"Section: {section[:50]}... -> {result}")

# 3. full datafram

In [3]:
df = pd.read_parquet("data/JOCAS/small/jocas_small_all_half_sirenised_embed_job_title.parquet")

In [4]:
import re
from transformers import AutoTokenizer

In [5]:
MODEL_NAME = "almanach/moderncamembert-base"
TEXT_COL = "description"

def minimal_clean(text):
    if pd.isna(text):
        return ""
    text = str(text).strip()
    text = re.sub(r"\s+", " ", text)
    return text

df["full_text"] = df[TEXT_COL].apply(minimal_clean)
df = df[df["full_text"].str.len() > 0].copy()

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def count_tokens(text):
    return len(tokenizer(text, add_special_tokens=True, truncation=False)["input_ids"])

df["n_tokens"] = df["full_text"].apply(count_tokens)

print(df["n_tokens"].describe(percentiles=[0.5, 0.75, 0.9, 0.95, 0.99]))

for limit in [256, 512, 768, 1024, 2048, 4096, 8192]:
    pct = (df["n_tokens"] <= limit).mean() * 100
    print(f"Offres <= {limit:>4} tokens : {pct:.1f}%")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (10691 > 8192). Running this sequence through the model will result in indexing errors

count    776465.000000
mean        360.879013
std         274.155651
min           3.000000
50%         309.000000
75%         474.000000
90%         663.000000
95%         805.000000
99%        1166.000000
max       79160.000000
Name: n_tokens, dtype: float64
Offres <=  256 tokens : 40.6%
Offres <=  512 tokens : 79.2%
Offres <=  768 tokens : 94.0%
Offres <= 1024 tokens : 98.2%
Offres <= 2048 tokens : 99.9%
Offres <= 4096 tokens : 100.0%
Offres <= 8192 tokens : 100.0%

In [ ]:
df

,ID_JOCAS,annee,mois,entreprise_nom,location_zipcode,description,job_ROME_code,contractType,SIREN,NAF_Code,Employee_Range,Company_Category,Director_Birth_Year,Company_Creation_Date,description_clean,embedding,embedding_pca,job_title,full_text,n_tokens
0,api_poleemploi_2023-04-28_78538,2023,4,NaN,31000,vous serez responsable du food truck pendant l...,G1401,CDI,,,,,,,vous serez responsable du food truck pendant l...,"[-0.037508223, 0.0065497477, -0.0007974197, -0...","[-0.037707433, 0.068371095, -0.09466716, -0.07...",Assistant / Assistante manager en restauration...,vous serez responsable du food truck pendant l...,115
1,jobintree_2023-05-19_48068,2023,5,aunis sud,NaN,description du poste :avec des clients dans pl...,M1707,CDI,200041614,84.11Z,NaN,PME,0.0,2014-01-01,description du poste :avec des clients dans pl...,"[-0.06067792, 0.024671966, -0.024764137, -0.06...","[-0.021875896, 0.014739902, 0.020539891, -0.12...",business developer (h/f),description du poste :avec des clients dans pl...,573
2,hellowork_bureau_etude_r_d_2023-03-17_1065,2023,3,NaN,NaN,vous êtes issu d'une formation supérieure typ...,,NaN,,,,,,,vous êtes issu d'une formation supérieure type...,"[-0.10698657, -0.06519823, -0.10766974, -0.079...","[-0.14357577, -0.23011383, 0.04959557, -0.0691...",,vous êtes issu d'une formation supérieure type...,253
3,jobintree_2023-06-07_33116,2023,6,win sport school,56000,"description du poste :win sport school vannes,...",M1705,Alternance,904549961,93.12Z,NaN,NaN,0.0,2021-10-13,description du poste :win sport school vannes ...,"[-0.010242393, 0.011192331, -0.062002324, -0.1...","[0.0026179682, -0.122466154, 0.050591026, -0.2...",chargé de marketing digital en alternance (h/f),"description du poste :win sport school vannes,...",292
4,hellowork_logistique_metiers_transport_2023-03...,2023,3,assystem,1150.0,qualifications vous recherchez une alternance...,N1301,CDI,412076937,70.10Z,NaN,ETI,1968,1997-04-26,qualifications vous recherchez une alternance ...,"[-0.09042679, -0.088197626, -0.04862888, -0.04...","[-0.10935141, -0.059904385, -0.0069309566, -0....",Chargé d'Affaires Logistique - Alternance H/F,qualifications vous recherchez une alternance ...,635
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804992,JOBINTREE_2020-12-05_8970,2020,12,lustral,39100.0,"nous recherchons une gouvernant d'intérieur, m...",K1304,CDI,,,,,,,"nous recherchons une gouvernant d'intérieur, m...","[-0.063871354, -0.0012015791, -0.036611278, -0...","[-0.114256166, -0.05006772, 0.10313746, 0.1643...",Emploi gouvernant / gouvernante à domicile (h/f),"nous recherchons une gouvernant d'intérieur, m...",381
804993,JOBINTREE_2020-01-24_77816,2020,1,la pie verte,31700.0,préparation de commandes et livraisons de repa...,N4105,CDD,,,,,,,préparation de commandes et livraisons de repa...,"[-0.07240109, 0.0437684, -0.037568178, -0.0340...","[-0.07467285, -0.12754369, 0.06715377, 0.07164...",Emploi chauffeur-livreur préparateur / chauffe...,préparation de commandes et livraisons de repa...,318
804994,JOBINTREE_2020-02-20_19748,2020,2,jvs mairistem,51520.0,tes missions : au sein de notre service commer...,D1401,CDI,,,,,,,tes missions : au sein de notre service commer...,"[-0.099452265, -0.014010274, -0.037381187, -0....","[-0.08108935, -0.23834908, 0.14693095, -0.1298...",Emploi commercial / commerciale sédentaire (h/f),tes missions : au sein de notre service commer...,232
804995,API_POLEEMPLOI_2020-10-28_4237,2020,10,NaN,49700.0,description du poste :\nvous mettez en œuvre d...,F1703,MIS,,,,,,,description du poste : vous mettez en œuvre de...,"[-0.065282054, 0.10251117, -0.017559458, -0.05...","[0.04462664, 0.1744917, -0.2265024, -0.1451148...",Maçon / Maçonne (H/F),description du poste : vous mettez en œuvre de...,140
804996,API_POLEEMPLOI_2020-10-27_5335,2020,10,elysee concept,17300.0,le premier concept de 'brocante permanente' en...,D1504,Franchise,384432688,70.22Z,NaN,PME,1947.0,1992-01-01,le premier concept de 'brocante permanente' en...,"[-0.06465209, -0.042722177, -0.07362445, -0.11...","[-0.115938574, -0.012959643, -0.0076625524, -0...",Directeur / Directrice de grand magasin,le premier concept de 'brocante permanente' en...,178

:

In [91]:
import sys
print(sys.executable)

c:\Users\benjamin.lengereau\AppData\Local\Programs\Python\Python313\python.exe